# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'g_sign_in' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for g_sign_in
  pod 'Google/SignIn'
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'g_sign_inTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'g_sign_inUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
